name: Deploy to sof-car.eu

on:
  push:
    branches: [main]
  workflow_dispatch: # –ü–æ–∑–≤–æ–ª—è–≤–∞ —Ä—ä—á–Ω–æ —Å—Ç–∞—Ä—Ç–∏—Ä–∞–Ω–µ

jobs:
  deploy:
    name: üöÄ Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: üöö Get latest code
        uses: actions/checkout@v4

      - name: üìÇ Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: sof-car.eu
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/sof-car.eu/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
            **/.gitignore
            **/.cpanel.yml
            **/deploy.log
          dry-run: false
